In [2]:
try:
    # %tensorflow_version only exists in Colob
    %tensorflow_version 2.x
except Exception:
    pass

In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.4.1


In [4]:
#生成序列数据
dataset = tf.data.Dataset.range(10)
for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [9]:
# 获得窗口数据，窗口大小为5
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1,drop_remainder=True)
for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(),end=" ")
    print()
    

0 1 2 3 
4 
1 2 3 4 
5 
2 3 4 5 
6 
3 4 5 6 
7 
4 5 6 7 
8 
5 6 7 8 
9 


In [7]:
# 转为numpy列表
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1,drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window:(window[:-1],window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2)#.prefetch(1)
for x,y in dataset:
    print(x.numpy(),y.numpy())

[[4 5 6 7]
 [5 6 7 8]] [[8]
 [9]]
[[2 3 4 5]
 [3 4 5 6]] [[6]
 [7]]
[[0 1 2 3]
 [1 2 3 4]] [[4]
 [5]]
